---
services:
  app:
    image: koti03/robotic_car_rasp:latest
    # platform: linux/amd64
    container_name: vehicle_real
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    # devices:
    #   - /dev/ttyUSB0

    # volumes:
    #   - ./lastpossition.json:/app/lastpossition.json