---
services:
  app:
    image: robotic_car:latest
    container_name: vehicle
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    # volumes:
    #   - ./lastpossition.json:/app/lastpossition.json